eCommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('myapp/',include('myapp.urls')),


]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp import views
app_name='myapp'

urlpatterns=[
    path('ContactPage/',views.ContactPage,name='ContactPage'),
    path('dashboard/',views.dashboard,name='dash'),
    path('first/',views.first,name='first'),
    path('about/',views.about,name='about'),
    path('login/',views.uslogin,name='login'),
    path('logout/',views.uslogout,name='logout'),
    path('view_profile/',views.view_profile,name='view_profile'),
    path('change_password/',views.change_password,name='change_password'),
    path('change_profile/',views.change_profile,name='change_profile'),
    path('registerView/',views.registerView,name='registerView'),
    path('checkUser/',views.checkUser,name='checkUser'),
    path('mobile/',views.mobile,name='mobile',),
    path('getproduct/',views.getproduct,name='getproduct',),
    path('addcart/',views.addcart,name='addcart',),
    path('forgot_password/',views.forgot_password,name='forgot_password',),
    path('find_user/',views.find_user,name='find_user',),
    path('my_orders/',views.my_orders,name='my_orders',),
    path('order_details/',views.order_details,name='order_details',),
    path('pending_orders/',views.pending_orders,name='pending_orders',),
    path('removeCart/',views.removeCart,name='removeCart',),
    path('grandTotal/',views.grandTotal,name='grandTotal',),
    path('get_order/',views.get_order,name='get_order',),
    path('success_payment/',views.success_payment,name='success_payment',),
    path('sendMail/',views.sendMail,name='sendMail',),
    path('profile/',views.profile,name='profile'),
    path('front/',views.front,name='front'),
    path('singleproduct/',views.singleproduct,name='singleproduct'),

]

templates/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from myapp.models import customer,product,category,cart,order,mail
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib import messages
import math
from django.db.models import Q
import random
import json
import datetime

from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMessage
from django.urls import reverse

@csrf_exempt
def payment_done(request):
    return HttpResponse('Payment Successful')
@csrf_exempt
def payment_canceled(request):
    return HttpResponse('Payment Canceled')


#categories
cat = category.objects.filter(sub_cat=None)


# Create your views here.
def base(request):
    return render(request,'base.html')

def getproduct(request):
    if 'cat' in request.GET:
            c = request.GET['cat']
            catobject = category.objects.get(category_name=c)
            dt = category.objects.filter(sub_cat=catobject).values()
            ab = []
            for i in dt:
                sub_cat = category.objects.get(id=i['id'])
                ab += list(product.objects.filter(product_category=sub_cat).values())
            products = product.objects.filter(product_category=catobject).values()
            allproducts = list(products)
            final = ab+allproducts
            return JsonResponse(final,safe=False)
import json
def singleproduct(request):
    if 'prid' in request.GET:
            id = request.GET['prid']
            singlep =product.objects.get(id=id)
            abcd = {"id":singlep.id,"name":singlep.product_name,"price":str(singlep.price),"sale_price":str(singlep.sale_price),"photo":str(singlep.photo),"description":singlep.description}
            dump = json.dumps(abcd)
            return HttpResponse(dump, content_type='application/json')
    return render(request,'front.html')

def front(request):
    alls = product.objects.all().order_by('-id')[:4]

    if request.method=='GET':
        if 'cat' in request.GET:
            c = request.GET['cat']
            catobject = category.objects.get(category_name=c)
            dt = category.objects.filter(sub_cat=catobject).values()
            ab = []
            for i in dt:
                sub_cat = category.objects.get(id=i['id'])
                ab += list(product.objects.filter(product_category=sub_cat).values())
            products = product.objects.filter(product_category=catobject).values()
            allproducts = list(products)
            final = ab+allproducts
            return JsonResponse(final,safe=False)
    return render(request,'front.html',{'cat':cat,'alls':alls})

def about(request):
    return render(request,'aboutus.html')

def usermail(request):
    if request.method == 'POST':

        name = request.POST['Name']
        email = request.POST['Email']
        phone = request.POST['Telephone']
        msz = request.POST['message']

        message = mail(name=name, email=email, phone=phone,message=msz)
        message.save()
        return render(request,'mailus.html',{'cat':cat,'status':True,'name':name})
    return render(request,'mailus.html',{'cat':cat})



def mobiles(request):
    all = product.objects.all()
    cat = category.objects.filter(sub_cat=None)
    alls = product.objects.all().order_by('-id')[:5]
    
    if 'prid' in request.GET:
            id = request.GET['prid']
            singlep =product.objects.get(id=id)
            abcd = {"id":singlep.id,"name":singlep.product_name,"price":str(singlep.price),"sale_price":str(singlep.sale_price),"photo":str(singlep.photo),"description":singlep.description}
            dump = json.dumps(abcd)
            return HttpResponse(dump, content_type='application/json')

    return render(request,'mobiles.html',{'all':all,'cat':cat,'alls':alls})



@login_required
def dashboard(request):
    return render(request,'dashboard.html')

@login_required
def profile(request):
    user = User.objects.get(username= request.user.username)
    reg = customer.objects.get(user=user)
    return render(request,'myprofile.html',{'data':user,'profile':reg})


def change_profile(request):
    user = User.objects.get(username= request.user.username)
    reg = customer.objects.get(user=user)
    if request.method =="POST":
        us = request.POST['username']
        em = request.POST['email']
        dob = request.POST['dob']
        add = request.POST['address']

        if us !="" or em !="" or dob !="" or add !="" :
            user.username = us
            user.email=em
            user.save()
            reg.address=add
            reg.dob = dob
            reg.save()
            return render(request,'changeprofile.html',{'data':user,'profile':reg,'status':'Changes saved successfully!!','c':'success'})
        else:
            return render(request,'changeprofile.html',{'data':user,'profile':reg,'status':'Changes are not saved!!','c':'danger'})

    return render(request,'changeprofile.html',{'data':user,'profile':reg})


from django.contrib.auth.hashers import check_password
@login_required
def change_password(request):
    user = User.objects.get(username= request.user.username)
    login_user_password = request.user.password
    if request.method == "POST":
        current = request.POST['old']
        newpass = request.POST['new']

        check = check_password(current,login_user_password)
        if check==True:
            user.set_password(newpass)
            user.save()
            # print("Matched!!!")
            return render(request,'changepassword.html',{'status':'Password changed successfully','col':'success'})

        else:
             return render(request,'changepassword.html',{'status':'invalid password','col':'danger'})
    return render(request,'changepassword.html')


def uservalid(request):
    if request.method=='GET':
        if 'username' in request.GET:
            un = request.GET['username']
            check = User.objects.filter(username=un)
            if(len(check)>0):
                return HttpResponse('A user with this name already exists')
            
            else:
                return HttpResponse('Success')

def registration(request):
   
    if request.method=="POST":
        name = request.POST['name']
        em = request.POST['email']
        ps = request.POST['password']
        pic = request.FILES['image']
        gender = request.POST['gender']
        dob = request.POST['dob']       
        
        check = User.objects.filter(username=em)
        if(len(check)>0):
            return render(request,'front.html',{'status':'user with this name already exists!!'})
        
        else:
            
            user = User.objects.create_user(em,em,ps)
            user.first_name=name
            user.save()

            prof=customer(user=user,profile=pic,date_of_birth=dob,gender=gender)
            prof.save()
            return render(request,'front.html',{'status':'Registred Successfully!!'})
    return render(request,'front.html')


def uslogin(request):
    if request.method == 'POST':
        usname = request.POST['email']
        pwd = request.POST['password']
        print('User = ',usname)
        user = authenticate(username=usname,password=pwd)
        if user:
            if user.is_staff:
                login(request,user)
                response= HttpResponseRedirect('/')
                response.set_cookie('username',usname)
                response.set_cookie('id',user.id)
                response.set_cookie('logintime',datetime.datetime.now())
                return response
            elif user.is_active:
                login(request,user)
                response= HttpResponseRedirect('/')
                response.set_cookie('username',usname)
                response.set_cookie('id',user.id)
                response.set_cookie('logintime',datetime.datetime.now())
                return response
            
        else:
            return render(request,'front.html',{'status': 'Invalid User Details'})
    return render(request,'front.html')



def uslogout(request):
    logout(request)
    response = HttpResponseRedirect('/')
    response.delete_cookie('username')
    return response




def addcart(request):
    if not request.user.is_authenticated:
        return render(request,'cart.html',{'status':'You Need To Login First'})
    user = User.objects.get(username=request.user.username)
    viewCart = cart.objects.filter(user_id=user)
    total_cart = []
    if request.method == 'POST':
        print(request.POST)
        item = request.POST['item_id']
        price = request.POST['amount']
        qty = request.POST['add']

        
        check = cart.objects.all()
        pro = product.objects.get(id=item)
        exist = False
        for x in check:
            if x.product_id==pro and x.user_id==user:
                exist=True          
        if exist is True:  
            messages.warning(request,'Item Already in Your Cart')
        else:
            saveCart = cart(user_id=user, product_id=pro, quantity=qty)
            saveCart.save()
            messages.success(request,'Item Added to Your Cart')
    
    if 'q' in request.GET:
        newQ = request.GET['q']
        cartId = request.GET['id']
        getCart = cart.objects.get(id=cartId)
        getCart.quantity = newQ            
        getCart.save() 
        details = {
            'quantity':getCart.quantity,
            'sale_price':getCart.product_id.sale_price,
            'price':getCart.product_id.price,
            'cart_size':len(viewCart),
        }          
        return JsonResponse(details)
    cid = ''
    for x in viewCart:
        cid+=str(x.id)+'/'
        user_cart = {}
        user_cart['id'] = x.id
        user_cart['product_name'] = x.product_id.product_name

templates/cart.html
{%extends "dashboard.html" %}
{% load staticfiles %}
{% block dashcode %}
<style>
    .spinnerouter{
        background:rgb(0,0,0,0.5);position:fixed;width: 100%;height: 100%;z-index:99999;
        top:0px;display: none;}
    .loader {
        border: 16px solid #f3f3f3; /* Light grey */
        border-top: 16px solid rgb(60, 67, 164); /* Blue */
        border-radius: 50%;
        width: 120px;
        height: 120px;
        animation: spin 1s linear infinite;
        position: absolute;
        left:45%;
        top:45%;
        z-index:999999;
    }
    .spinner-border{
        height:25px;width:25px;border:5px solid white;border-top:5px solid #f0ad4e;
        animation: spin 1s linear infinite;border-radius:50%;margin:auto;
    }
    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
    table,td{
    color:black !important;
   }


</style>
<div class="spinnerouter">
    <div class="loader">

    </div>
</div>
<div class='row py-5'>
    <div class='col-md-12' style=" font-family:'Vollkorn',serif;">
        <h2 class='mt-5'>My Cart</h2>
        <div class='col-md-12' style=" font-family:'Vollkorn',serif;">
                {% if messages %}
                {% for i in messages %}
                    <div class="alert alert-{{i.tags}} status">{{i}}</div>
                {% endfor %}
                {% endif %}
            </div>
            {% if cart_size is 0 %}
            <div class='col-md-12' style='padding:20px;' id='empty'>
                <h2 style=" font-family:'Vollkorn',serif;">❌ Your Shopping Cart is Empty</h2>
            </div>
            {% else %}
            <div class='row' id='fill'>
                <div class='col-md-8'>
                    <h2>My Cart(<span id='csize'>{{cart_size}}</span> )</h2>
                    <hr/>
                    <ul class='list-group' style=" font-family:'Vollkorn',serif;">
                        {% for i in cart %}
                        <li class='list-group-item c-{{i.id}}' style='box-shadow:0px 0px 10px black;'>
                            <div class='row'>
                                <div class='col-md-9' style='text-align:center;font-size:30px;'>
                                    <span>
                                        <img src="/media/{{i.photo}}" style='margin:10px;' height='200' width='200' class=''>
                                        <div class='form-group'>
                                            <div class='row'>
                                                <div class='col-md-3 col-sm-3 col-3'>
                                                    <span onclick="addNum('{{i.id}}','add')">
                                                        <i class="fas fa-plus-circle text-success"></i>
                                                    </span>
                                                </div>
                                                <div class='col-md-6 col-sm-6 col-6'>
                                                    <input type="number" id="num" value='{{i.quantity}}' class='form-control num{{i.id}}'>
                                                </div>
                                                <div class='col-md-3 col-sm-3 col-3'>
                                                    <span onclick="addNum('{{i.id}}','sub')">              
                                                        <i class="fas fa-minus-circle text-danger"></i>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </span>
                                </div>
                                <div class='col-md-9'>
                                    <span class='text-danger font-weight-bold' style=" font-family:'Vollkorn',serif;">
                                        <strong>{{i.product_name}}</strong><br/>
                                        |{{i.product_cat}} |
                                    </span>
                                    <h4 STYLE='margin-top:20px; font-family:'Vollkorn',serif;'><strong class='text-success cartsaleprice{{i.id}}'>&#8377;{{i.price}}</strong> <del style='font-size:12px;' class='cartprice{{i.id}}'> &#8377; {{i.market}}</del>
                                        <span style='color:green;font-family:arial'>You save {{i.offer}}%</span>
                                    </h4>
                                </div>
                            </div> 
                            <hr/>
                        </li>           
                        {% endfor %}
                    </ul>    
                </div>
                <div class='col-md-4' style=" font-family:'Vollkorn',serif;">
                    {% if cart_size is not  0 %}
                    <h2>Price Details</h2>
                    <hr/>
                    <div style='border:1px solid gray;padding:10px;border-radius:5px;'>
                        <table class='table'style=" font-family:'Vollkorn',serif;">
                            <tbody>
                                <tr>
                                    <td id='itotal'>ITEM TOTAL</td>
                                    <td id='total'></td>
                                </tr>
                                <tr style='border-bottom:1px dotted gray;'>
                                    <td>DELIVERY CHARGES</td>
                                    <td>FREE</td>
                                </tr>
                                <tr>
                                    <td><strong>GRAND TOTAL</strong></td>
                                    <td id='grand'></td>
                                </tr>
                                
                            </tbody>
                        </table>
                        <hr/>
                        <div style='padding:10px; display:none;  font-family:"Vollkorn",serif;' id='delivery_address'>
                            <h4>Enter Delivery Details</h4>
                            <hr/>
                            
                                <div class='form-group'>
                                    <input type="text" class='form-control' placeholder='Enter Name' id='dname' required>
                                </div>
                                <div class='form-group'>
                                    <!-- <label for="" id='res'></label> -->
                                    <input type="email" class='form-control' placeholder='Enter Email Address' id='demail' required>
                                </div>
                                <!-- <div class='form-group' style='display:none;'>
                                    <input type="number" class='form-control' placeholder='Enter OTP Here' id='id_enter_otp'>
                                </div> -->
                                <div class='form-group'>
                                    <input type="number" class='form-control' placeholder='Enter Mobile Number' id='dnumber' required>
                                </div>
                                <div class='form-group'>
                                    <textarea name="daddress" id="daddress" class='form-control' placeholder='Enter Full Address' required></textarea>
                                </div>
                                <div class='form-group'>
                                    <input type="hidden" id='grandtotal'>
                                    <input type="hidden" id='items' value='{{cids}}'>
                                    
                                    <input type="radio" name="pay"  value="OP" checked>Online Payment
                                    <input type="radio" name="pay"  value="COD">Cash On Delivery
                                    <button class='btn btn-success btn-block' id='ptp'>Proceed To Pay</button>
                                </div>
                            
    
                        </div>
                        <button class='btn btn-warning btn-block' style=" font-family:'Vollkorn',serif;" id='ptb'><i class='fas fa-shopping-cart'></i> Proceed To Buy</button>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    <script>
    function addNum(id,action){
        $('.spinnerouter').show();
        let v = $('.num'+id).val();
        let updateQuant = 0;
        if(action=='add'){
            updateQuant = parseInt(v)+1;    
        }else{
            updateQuant = parseInt(v)-1;    
        }
        setTimeout(function(){
            $.ajax({
                url:'{% url "myapp:addcart" %}',
                type:'get',
                data:{q:updateQuant,id:id},
                success:function(data){
                    $('.num'+id).val(data.quantity);
                    $('.cartsaleprice'+id).html(data.sale_price*data.quantity);
                    $('.cartprice'+id).html(data.price*data.quantity);
                    $('.spinnerouter').hide();
                    $('#csize').html(data.cart_size);
                    grandTotal()
    
                    // #Remove Items
                    if(data.quantity==0){
                    $.ajax({
                        url:'{% url "myapp:removeCart" %}',
                        data:{removeid:id},
                        success:function(data){
                            $('.c-'+id).hide();
                            $('.status').html(data.msz);
                            $('#csize').html(data.cart_size);
                        }
                    });
                }              
                }
            });
        });
    }
    </script>
    
    <script>
        let email;
    function grandTotal(){
        $.ajax({
            url:'{% url "myapp:grandTotal" %}',
            success:function(data){
               
                $('#itotal').html('ITEM TOTAL ('+data.quantity+')');
                $('#total').html('&#8377;'+data.grand_total);
                $('#grand').html('&#8377;'+data.grand_total);
                $('#demail').val(data.email)
                $('#dname').val(data.name)
                $('#daddress').val(data.address)
                $('#grandtotal').val(data.grand_total);
                $('#ptp').html('Proceed To Pay &#8377;'+ data.grand_total)
            }
        });
    }
    
    </script>
    <script>
    $(function(){
        grandTotal();
    })
    </script>
    <script>
    $('#ptb').click(function(){
        $(this).html('<div class="spinner-border"></div>');
        setTimeout(function(){
            $('#delivery_address').slideDown(1000);
            $('#ptb').hide();
        },1500);
    });
    </script>
    
    <!-- VERIFICATION EMAIL --> 
    <script>
    var arr = [];
    $('#dnu').focus(function(){
        var name = $('#dname').val();
        var email = $('#demail').val();
        $.ajax({
        url:'{% url "myapp:sendMail" %}',
        data:{name:name,email:email},
        success:function(data){
            arr = data.split('@');
            $('#res').html(arr[0]).addClass('text-success');
            $('#id_enter_OTP').show();
        }
        });
    });
    </script>
    
    <script>
    $('#ptp').click(function(){
        let dname = $('#dname').val();
        let demail = $('#demail').val();
        let daddr =$('#daddress').val();
        let dcon = $('#dnumber').val();
        let amount = $('#grandtotal').val();
        let it = $('#items').val();
        let paymentmode = $('input[name=pay]:checked').val();
        
        $.ajax({
            url:'{% url "myapp:get_order"%}',
            type:'get',
            data:{'grandtotal':amount,'dname':dname,'demail':demail,'daddress':daddr,'dnumber':dcon,'items':it,'pay':paymentmode},
            success:function(data){
                
                if(data[0]==1){
                    url = '{% url "myapp:success_payment"%}?m=cod&id='+data[1];
                    window.location = url;
                }else{
                let oid = parseInt(data[1])+Math.round(Math.random()*(9999-1000)+1000)
                url = 'http://sachtechsolution.pe.hu/easypayment/payment.php?mid=NSYQPa91080304292250&amount='+amount+'&adminemail=jriya982@gmail.com&adminmobile=9779503460&mkey=CTVxe3C%23K1zy%23ux%25&orderid='+data+'o'+oid+'&returnurl=http://127.0.0.1:8000{% url "myapp:success_payment"%}';
                window.location = url; 
                }
            }
        })
        
    })
    </script>
{% endblock %}

templates/change_password.html
{% extends 'dashboard.html' %}
{% load staticfiles %}
{% block dashcode %}
    <div class='row py-5'>
        <div class='col-md-6 mx-auto' style="font-family:'Vollkorn',serif; background:rgba(255,255,255,0.7)">
            <h2 class='mt-5 text-center'>Change Password</h2>
        {% if status %}
            <p class='alert alert-{{col}}'>{{status}}
                <a href="{% url 'myapp:login' %}">Login Again!!</a> 
            </p>
        {% endif %}
        {% if status1 %}
            <p class='alert alert-{{col}}'>{{status1}}</p>
        {% endif %}
            <form action="" method='POST'>
            {% csrf_token %}
                <div class='form-group mt-5'>
                    <label for="">Current Password</label>
                    <input type="password" class='form-control' name='old' placeholder='Current Password'>
                </div>
                <div class='form-group'>
                    <label for="">New Password</label>
                    <input type="password" class='form-control' id='p' onkeyup='check()' name='new' placeholder='New Password'>
                </div>
                <div class='form-group'>
                    <label for="">Re-enter New Password</label>
                    <input type="password" class='form-control' id='cp' onkeyup='check()' name='rnew' placeholder='Re-enter New Password'>
                </div>
                <div class='form-group'>
                    <input type="submit" class='btn btn-primary btn-block' id='change' value='Change Password' disabled>
                </div>
            </form>
            </div>
    </div>
<script>
    function check(){
    pw=$('#p').val();
    cpw=$('#cp').val();
    if(pw==cpw){
    $("#p").css('border','solid green')
    $("#cp").css('border','solid green')
    $('#change').removeAttr('disabled');
    }
    else{
    $('#p').css('border','1px solid red');
    $('#cp').css('border','1px solid red');
    $('#change').attr('disabled','disabled'); 
    }
    }
</script>
{% endblock %}

templates/my_profile.html
{% extends "dashboard.html" %}
{% load staticfiles %}
{% block dashcode %}
    <div class='row py-5'>
        <div class='col-md-8 mx-auto py-5' style="font-family:'Vollkorn',serif; background:rgba(255,255,255,0.5);">
            <h2 class='text-center mt-5'>Details</h2>
            <table class='table table-striped'>
                <tr>
                    <th>Full Name</th>
                    <td>{{user.username}}</td>
                </tr>
                <tr>
                    <th>User Id</th>
                    <td>{{user.id}}</td>
                </tr>    
                <tr>
                    <th>Email</th>
                    <td>{{user.email}}</td>
                </tr>
                <tr>
                    <th>Mobile No.</th>
                    <td>{{profile.mobile_no}}</td>
                </tr>
                <tr>
                    <th>Address</th>
                    <td>{{profile.address}}</td>
                </tr>
                <tr>
                    <th>Registered On</th>
                    <td>{{profile.registered_on}}</td>
                </tr>

            </table>
        </div>
    </div>
{% endblock %}

templates/orders.html
{% extends "dashboard.html" %}
{% load staticfiles %}
{% block style %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src='//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js'></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'mystyle.css'%}">
<style>
.ab{
    border:1px solid black !important;
}
</style>
{% endblock %}
{% block dashcode %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<div class='row'>
    <div class='col-md-12'>
            <h2 class='py-5'>Order History</h2>
        <table class='table table-striped table-hover' id='mytable' style=" font-family:'Vollkorn',serif;">
            <thead>
                <tr>
                    <th>Order Id</th>
                    <th>Total Price</th>
                    <th>Received On</th>
                    <th>Processed On</th>
                    <th>Payment Mode</th>
                    <th>View Items</th>
                </tr>
            </thead>
            <tbody>
                    {% for i in all_orders %}
                        <tr>
                            <td>{{i.id}}</td>
                            <td>{{i.amount}}</td>
                            <td>{{i.received_on}}</td>
                            <td>{{i.changed_on}}</td>
                            <td>{{i.payment_mode}}</td>
                            <td>
                                <a href="{% url 'myapp:order_details'%}?id={{i.id}}"><button class='btn btn-sm btn-primary'>View</button></a>
                            </td>
                            
        
                        </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>
</div>
<script>
        $(function(){
            $('#myTable').DataTable();
        })
        </script>
{% endblock %}

templates/pending.html
{% extends "dashboard.html" %}
{% load staticfiles%}
{% block style %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src='//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js'></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'mystyle.css'%}">
<style>
.ab{
    border:1px solid black !important;
}
</style>
{% endblock %}
{% block dashcode %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <h2 class='py-5'>Pending Orders</h2>
    <table class='table table-striped table-hover table-bordered' id='myTable' style=" font-family:'Vollkorn',serif;">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Total Price</th>
                <th>Received On</th>
                <th>Processed On</th>
                <th>View Items</th>
            </tr>
        </thead>
        <tbody>
            {% for i in pending_orders %}
                <tr>
                    <td>{{i.id}}</td>
                    <td>{{i.amount}}</td>
                    <td>{{i.received_on}}</td>
                    <td>{{i.changed_on}}</td>
                    <td>
                        <a href="{% url 'myapp:order_details'%}?id={{i.id}}"><button class='btn btn-sm btn-primary'>View</button>
                    </td>

                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
    $(function(){
        $('#myTable').DataTable();
    })
    </script>
{% endblock %}